server:
  assets-path: /app/assets

theme:
  background-color: "#0f0f12"
  primary-color: "#d4af37"
  contrast-multiplier: 1.1
  custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: tech.yml
  - $include: media.yml
  - $include: nsy.yml