server:
  assets-path: /app/assets

theme:
  background-color: "hsl(250, 20%, 95%)"
  primary-color: "hsl(250, 60%, 20%)"
  contrast-multiplier: 1.0
  custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: tech.yml
  - $include: media.yml
  - $include: nsy.yml