- name: Media
  columns:
    - size: full
      widgets:
        - type: rss
          title: YouTube Subscriptions
          limit: 5
          feeds:
            - url: https://rsshub.app/youtube/user/LinusTechTips
              title: LTT
        - type: rss
          title: Movie News
          limit: 5
          feeds:
            - url: https://rsshub.app/douban/movie/later
              title: 豆瓣电影