columns:
  - size: small
    widgets:
      - type: extension
        title: System Load
        url: http://localhost:8080/api/system
  - size: full
    widgets:
      - type: monitor
        title: Infrastructure
        sites:
          - title: Zeabur Dashboard
            url: https://dash.zeabur.com
          - title: GitHub Status
            url: https://www.githubstatus.com